apiVersion: 1

datasources:
  - name: Cloud Monitor PostgreSQL
    uid: cloud-monitor-postgres
    type: postgres
    access: proxy
    url: ${GRAFANA_POSTGRES_HOST}:${GRAFANA_POSTGRES_PORT}
    user: ${GRAFANA_POSTGRES_USER}
    editable: false
    isDefault: true
    jsonData:
      database: ${GRAFANA_POSTGRES_DATABASE}
      sslmode: ${GRAFANA_POSTGRES_SSLMODE}
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: ${GRAFANA_POSTGRES_PASSWORD}
